FROM node:lts-slim as build-step

COPY ./frontend /frontend
WORKDIR /frontend

RUN npm install -g serve
RUN yarn
RUN yarn build

FROM caddy:alpine
EXPOSE 80
EXPOSE 443
COPY --from=build-step /frontend/build /usr/share/caddy