version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 1245:80
    networks:
      - app_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.ligma
    container_name: apihost
    networks:
      - app_network

networks:
  app_network:
    driver: bridge