-- ALTER TABLE article_author DISABLE TRIGGER ALL;
-- ALTER TABLE articles DISABLE TRIGGER ALL;
-- ALTER TABLE art_references DISABLE TRIGGER ALL;
-- ALTER TABLE article_tags DISABLE TRIGGER ALL;

-- ALTER TABLE article_author ENABLE TRIGGER ALL;
-- ALTER TABLE articles ENABLE TRIGGER ALL;
-- ALTER TABLE art_references ENABLE TRIGGER ALL;
-- ALTER TABLE article_tags ENABLE TRIGGER ALL;